before:
  hooks:
    - go mod tidy
builds:
  - 
    binary: hsnap
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      #- arm
      #- windows
      #- darwin
    goarch:
      - arm
      - amd64
    goarm:
      - 5
    ldflags:
      - -s -w -X main.build={{.Version}}
archives:
  - replacements:
      #darwin: Darwin
      linux: Linux
      #windows: Windows
      #386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
